# © 2025 Awais Mughal. All rights reserved.
# Unauthorized commercial use is prohibited.


# Docker Compose configuration for SONA AI Assistant
services:
  # SONA Backend Service
  sona-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sona-backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: python backend/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - sona-network
    
  # SONA Frontend Service  
  sona-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sona-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_PORT=8501
      - BACKEND_HOST=sona-backend
      - BACKEND_PORT=8000
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "
        echo 'Waiting for backend to be ready...' &&
        sleep 10 &&
        streamlit run ui/streamlit_app.py 
        --server.port=8501 
        --server.address=0.0.0.0 
        --server.headless=true 
        --browser.serverAddress=localhost 
        --browser.gatherUsageStats=false
      "
    depends_on:
      sona-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sona-network

# Networks
networks:
  sona-network:
    driver: bridge
    name: sona-network
